(()=>{
'use strict';
const $=id=>document.getElementById(id);
const field=()=>$('calcMathField');
let activeSlot=null,last={source:'',exactLatex:'',decimal:null},degrees=false,returnFocus=null;
const rec=(type,detail)=>window.TD?.record?.(type,detail,{category:'calculator'});
const typeset=async nodes=>{const list=(nodes||[]).filter(Boolean);if(!list.length||!window.MathJax)return;try{await window.MathJax.startup?.promise;window.MathJax.typesetClear?.(list);await window.MathJax.typesetPromise?.(list)}catch(err){console.error('MathJax calculator error',err)}};
function gcd(a,b){a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a||1n}
function rat(n,d=1n){n=BigInt(n);d=BigInt(d);if(d===0n)throw Error('División por cero');if(d<0n){n=-n;d=-d}const g=gcd(n,d);return{n:n/g,d:d/g}}
function ratText(s){s=String(s);if(!s.includes('.'))return rat(BigInt(s));const [a,b='']=s.split('.'),neg=a.startsWith('-'),ai=a.replace('-','')||'0';return rat((neg?-1n:1n)*BigInt(ai+b),10n**BigInt(b.length))}
const radd=(a,b)=>rat(a.n*b.d+b.n*a.d,a.d*b.d),rsub=(a,b)=>rat(a.n*b.d-b.n*a.d,a.d*b.d),rmul=(a,b)=>rat(a.n*b.n,a.d*b.d),rdiv=(a,b)=>rat(a.n*b.d,a.d*b.n);
function rpow(a,k){k=Number(k);if(!Number.isInteger(k))return null;if(k===0)return rat(1);if(k<0){const z=rpow(a,-k);return rat(z.d,z.n)}return rat(a.n**BigInt(k),a.d**BigInt(k))}
function rlatex(r){if(r.d===1n)return String(r.n);return `${r.n<0n?'-':''}\\frac{${r.n<0n?-r.n:r.n}}{${r.d}}`}
function tokenize(src){let s=String(src||'').replace(/π/g,'pi').replace(/×/g,'*').replace(/÷/g,'/').replace(/[−–—]/g,'-').replace(/(\d),(\d)/g,'$1.$2').replace(/\bsen\b/gi,'sin').trim();const out=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let j=i+1;while(j<s.length&&/[0-9.]/.test(s[j]))j++;const v=s.slice(i,j);if(!/^\d*\.?\d+$/.test(v)||v==='.')throw Error('Número no válido');out.push({t:'num',v});i=j;continue}if(/[A-Za-z_]/.test(c)){let j=i+1;while(j<s.length&&/[A-Za-z_]/.test(s[j]))j++;out.push({t:'id',v:s.slice(i,j).toLowerCase()});i=j;continue}if('+-*/^()'.includes(c)){out.push({t:c,v:c});i++;continue}throw Error(`Símbolo no permitido: ${c}`)}out.push({t:'eof'});return out}
function parse(src){const t=tokenize(src);let p=0;const pk=()=>t[p],take=x=>{if(pk().t!==x)throw Error(`Se esperaba ${x}`);return t[p++]};let expr;const primary=()=>{const z=pk();if(z.t==='num'){p++;return{k:'num',v:z.v}}if(z.t==='id'){p++;if(['pi','e'].includes(z.v))return{k:'const',v:z.v};if(!['sin','cos','tan','sqrt','ln','log','exp','abs'].includes(z.v))throw Error(`Función no permitida: ${z.v}`);take('(');const a=expr();take(')');return{k:'fn',v:z.v,a}}if(z.t==='('){p++;const a=expr();take(')');return a}throw Error('Expresión incompleta')};const unary=()=>{if(pk().t==='+'||pk().t==='-'){const op=t[p++].t;return{k:'un',op,a:unary()}}return primary()};const power=()=>{let a=unary();if(pk().t==='^'){p++;a={k:'bin',op:'^',a,b:power()}}return a};const starts=z=>['num','id','('].includes(z.t);const term=()=>{let a=power();while(pk().t==='*'||pk().t==='/'||starts(pk())){const op=(pk().t==='*'||pk().t==='/')?t[p++].t:'*';a={k:'bin',op,a,b:power()}}return a};expr=()=>{let a=term();while(pk().t==='+'||pk().t==='-'){const op=t[p++].t;a={k:'bin',op,a,b:term()}}return a};const ast=expr();if(pk().t!=='eof')throw Error('Expresión no reconocida');return ast}
function numeric(n){if(n.k==='num')return Number(n.v);if(n.k==='const')return n.v==='pi'?Math.PI:Math.E;if(n.k==='un')return n.op==='-'?-numeric(n.a):numeric(n.a);if(n.k==='bin'){const a=numeric(n.a),b=numeric(n.b);return n.op==='+'?a+b:n.op==='-'?a-b:n.op==='*'?a*b:n.op==='/'?a/b:Math.pow(a,b)}const x=numeric(n.a),ang=degrees?x*Math.PI/180:x;return n.v==='sin'?Math.sin(ang):n.v==='cos'?Math.cos(ang):n.v==='tan'?Math.tan(ang):n.v==='sqrt'?Math.sqrt(x):n.v==='ln'?Math.log(x):n.v==='log'?Math.log10(x):n.v==='exp'?Math.exp(x):Math.abs(x)}
function rational(n){if(n.k==='num')return ratText(n.v);if(n.k==='un'){const a=rational(n.a);return a?rat(n.op==='-'?-a.n:a.n,a.d):null}if(n.k==='bin'){const a=rational(n.a),b=rational(n.b);if(!a||!b)return null;return n.op==='+'?radd(a,b):n.op==='-'?rsub(a,b):n.op==='*'?rmul(a,b):n.op==='/'?rdiv(a,b):n.op==='^'&&b.d===1n?rpow(a,b.n):null}return null}
function latex(n,parent=0){if(n.k==='num')return n.v;if(n.k==='const')return n.v==='pi'?'\\pi':'e';if(n.k==='un'){const z=(n.op==='-'?'-':'')+latex(n.a,3);return parent>3?`\\left(${z}\\right)`:z}if(n.k==='fn'){const a=latex(n.a);if(n.v==='sqrt')return `\\sqrt{${a}}`;if(n.v==='abs')return `\\left|${a}\\right|`;return `\\operatorname{${n.v==='sin'?'sen':n.v}}\\left(${a}\\right)`}const pr=n.op==='+'||n.op==='-'?1:n.op==='*'||n.op==='/'?2:3;let z=n.op==='/'?`\\frac{${latex(n.a)}}{${latex(n.b)}}`:n.op==='^'?`${latex(n.a,3)}^{${latex(n.b)}}`:n.op==='*'?`${latex(n.a,2)}\\,${latex(n.b,2)}`:`${latex(n.a,pr)} ${n.op} ${latex(n.b,pr+.1)}`;return pr<parent?`\\left(${z}\\right)`:z}
function exact(n){const r=rational(n);if(r)return rlatex(r);if(n.k==='fn'&&n.v==='sqrt'){const rr=rational(n.a);if(rr&&rr.d===1n&&rr.n>=0n){const x=Number(rr.n),q=Math.floor(Math.sqrt(x));if(q*q===x)return String(q)}}return latex(n)}
function format(x){if(Math.abs(x)<1e-13)x=0;return Number(x.toPrecision(12)).toString()}
function slot(name){const s=document.createElement('span');s.className='math-slot-editor';s.dataset.slot=name;s.contentEditable='true';return s}
function make(kind,preset=''){const o=document.createElement('span');o.className='math-structure';o.dataset.kind=kind;o.contentEditable='false';let first,primary,next=null;if(kind==='fraction'){o.classList.add('math-fraction');const a=slot('num'),b=slot('den');o.append(a,b);first=primary=a;next=b}else if(kind==='power'){o.classList.add('math-power');const a=slot('base'),sup=document.createElement('sup'),b=slot('exp');if(preset)b.textContent=preset;sup.append(b);o.append(a,sup);first=primary=a;next=preset?null:b}else if(kind==='sqrt'){o.classList.add('math-root');const sg=document.createElement('span'),rw=document.createElement('span'),a=slot('rad');sg.className='radical-sign';sg.textContent='√';rw.className='radicand';rw.append(a);o.append(sg,rw);first=primary=a}else if(kind==='nthroot'){o.classList.add('math-root','math-nth-root');const iw=document.createElement('sup'),idx=slot('idx'),sg=document.createElement('span'),rw=document.createElement('span'),a=slot('rad');iw.className='root-index';iw.append(idx);sg.className='radical-sign';sg.textContent='√';rw.className='radicand';rw.append(a);o.append(iw,sg,rw);first=idx;primary=a;next=idx}else if(kind==='abs'||kind==='paren'){o.classList.add(kind==='abs'?'math-abs':'math-paren');const l=document.createElement('span'),a=slot('arg'),r=document.createElement('span');l.className=r.className=kind==='abs'?'bar':'paren';l.textContent=kind==='abs'?'|':'(';r.textContent=kind==='abs'?'|':')';o.append(l,a,r);first=primary=a}else{const fn=kind==='sen'?'sin':kind;o.dataset.kind='function';o.dataset.fn=fn;o.classList.add('math-function');const f=document.createElement('span'),l=document.createElement('span'),a=slot('arg'),r=document.createElement('span');f.className='fn-name';f.textContent=fn==='sin'?'sen':fn;l.className=r.className='paren';l.textContent='(';r.textContent=')';o.append(f,l,a,r);first=primary=a}return{o,first,primary,next}}
function serializeNode(n){if(n.nodeType===Node.TEXT_NODE)return n.nodeValue.replace(/π/g,'pi').replace(/×/g,'*').replace(/÷/g,'/').replace(/[−–—]/g,'-');if(n.nodeType!==Node.ELEMENT_NODE)return'';const k=n.dataset.kind;if(!k)return serialize(n);if(k==='fraction'){const a=serialize(n.querySelector('[data-slot="num"]')),b=serialize(n.querySelector('[data-slot="den"]'));return `((${a})/(${b}))`}if(k==='power'){const a=serialize(n.querySelector('[data-slot="base"]')),b=serialize(n.querySelector('[data-slot="exp"]'));return `((${a})^(${b}))`}if(k==='sqrt')return `sqrt(${serialize(n.querySelector('[data-slot="rad"]'))})`;if(k==='nthroot'){const idx=serialize(n.querySelector('[data-slot="idx"]')),a=serialize(n.querySelector('[data-slot="rad"]'));return `((${a})^(1/(${idx})))`}if(k==='abs')return `abs(${serialize(n.querySelector('[data-slot="arg"]'))})`;if(k==='paren')return `(${serialize(n.querySelector('[data-slot="arg"]'))})`;return `${n.dataset.fn}(${serialize(n.querySelector('[data-slot="arg"]'))})`}
function serialize(root){return Array.from(root?.childNodes||[]).map(serializeNode).join('').replace(/\s+/g,'')}
function rangeFor(container){const sel=getSelection();if(sel?.rangeCount){const r=sel.getRangeAt(0);if(container.contains(r.commonAncestorContainer)||r.commonAncestorContainer===container)return r}const r=document.createRange();r.selectNodeContents(container);r.collapse(false);return r}
function focusEnd(el){el.focus();const r=document.createRange();r.selectNodeContents(el);r.collapse(false);const s=getSelection();s.removeAllRanges();s.addRange(r);activeSlot=el}
function current(){return activeSlot&&document.contains(activeSlot)?activeSlot:field()}
function insertText(v){const c=current();let shown=String(v);if(shown==='*')shown='×';if(shown==='/')shown='÷';if(shown==='-')shown='−';const r=rangeFor(c);r.deleteContents();const n=document.createTextNode(shown);r.insertNode(n);r.setStartAfter(n);r.collapse(true);const s=getSelection();s.removeAllRanges();s.addRange(r);c.focus();activeSlot=c;changed()}
function insertStruct(kind,preset=''){const c=current(),r=rangeFor(c),m=make(kind,preset);r.deleteContents();r.insertNode(m.o);changed();focusEnd(m.first)}
function del(){const c=current(),r=rangeFor(c);if(!r.collapsed){r.deleteContents();changed();return}if(r.startContainer.nodeType===Node.TEXT_NODE&&r.startOffset>0){r.startContainer.deleteData(r.startOffset-1,1);changed();return}if(r.startContainer.nodeType===Node.ELEMENT_NODE&&r.startOffset>0){r.startContainer.childNodes[r.startOffset-1]?.remove();changed();return}if(c!==field()&&!serialize(c)){const st=c.closest('[data-kind]'),p=st?.parentElement?.closest('.math-slot-editor')||field();st?.remove();focusEnd(p);changed()}}
function slots(){return [...field().querySelectorAll('.math-slot-editor')]}
function move(back=false){const a=slots(),c=document.activeElement?.classList.contains('math-slot-editor')?document.activeElement:activeSlot;let i=a.indexOf(c);const n=a[i+(back?-1:1)];if(n){focusEnd(n);return true}return false}
function changed(){last={source:'',exactLatex:'',decimal:null};$('calcStatus').textContent=''}
function evaluate(){try{if(slots().some(s=>!serialize(s)))throw Error('Completa todas las casillas de la plantilla');const source=serialize(field());if(!source)throw Error('Escribe una expresión');const ast=parse(source),decimal=numeric(ast);if(!Number.isFinite(decimal))throw Error('El resultado no es finito');last={source,exactLatex:exact(ast),decimal};$('calcExactOutput').innerHTML=`\\[${last.exactLatex}\\]`;$('calcDecimalOutput').innerHTML=`\\[${format(decimal)}\\]`;$('calcStatus').textContent='Resultado calculado y simplificado';setMode('exact');typeset([$('calcExactOutput'),$('calcDecimalOutput')]);rec('Cálculo realizado',`${source} = ${format(decimal)}`);return last}catch(e){$('calcStatus').textContent=e.message;$('calcExactOutput').textContent='—';$('calcDecimalOutput').textContent='—';throw e}}
function reset(){field().innerHTML='';activeSlot=field();last={source:'',exactLatex:'',decimal:null};$('calcExactOutput').innerHTML='\\(—\\)';$('calcDecimalOutput').innerHTML='\\(—\\)';$('calcStatus').textContent='';typeset([$('calcExactOutput'),$('calcDecimalOutput')]);focusEnd(field())}
function setMode(m){const ex=m==='exact';$('calcExactMode').classList.toggle('active',ex);$('calcDecimalMode').classList.toggle('active',!ex);$('calcExactCard').classList.toggle('active',ex);$('calcDecimalCard').classList.toggle('active',!ex)}
function open(){returnFocus=document.activeElement;$('calculatorPanel').classList.remove('hidden');$('calcBackdrop').classList.remove('hidden');rec('Apertura de calculadora','El estudiante abrió la calculadora durante una pregunta.');setTimeout(()=>focusEnd(field()),40)}
function close(){$('calculatorPanel').classList.add('hidden');$('calcBackdrop').classList.add('hidden');rec('Cierre de calculadora','El estudiante regresó a la pregunta.');returnFocus?.focus?.();returnFocus=null}
function init(){field().addEventListener('focusin',e=>{activeSlot=e.target.closest('.math-slot-editor')||field()});field().addEventListener('pointerdown',e=>{activeSlot=e.target.closest('.math-slot-editor')||field()});field().addEventListener('keydown',e=>{const s=e.target.closest('.math-slot-editor');if(e.key==='Tab'){if(move(e.shiftKey))e.preventDefault()}else if(e.key==='ArrowDown'&&s?.dataset.slot==='num'){const d=s.closest('[data-kind="fraction"]')?.querySelector('[data-slot="den"]');if(d){e.preventDefault();focusEnd(d)}}else if(e.key==='ArrowUp'&&s?.dataset.slot==='den'){const n=s.closest('[data-kind="fraction"]')?.querySelector('[data-slot="num"]');if(n){e.preventDefault();focusEnd(n)}}else if(e.key==='Enter'){e.preventDefault();try{evaluate()}catch{}}else if(e.key==='Backspace'&&s){e.preventDefault();del()}else if(s&&e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();insertText(e.key)}});document.querySelectorAll('[data-calc]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.calc;if(k==='clear')reset();else if(k==='back')del();else if(k==='equals'){try{evaluate()}catch{}}else insertText(k)}));document.querySelectorAll('[data-structure]').forEach(b=>b.addEventListener('click',()=>insertStruct(b.dataset.structure,b.dataset.power||'')));$('calcEvaluate').onclick=()=>{try{evaluate()}catch{}};$('calcClearField').onclick=reset;$('openCalculator').onclick=open;$('closeCalculator').onclick=close;$('calcBackdrop').onclick=close;$('calcExactMode').onclick=()=>setMode('exact');$('calcDecimalMode').onclick=()=>setMode('decimal');$('calcAngleMode').onclick=()=>{degrees=!degrees;$('calcAngleMode').textContent=degrees?'Grados':'Radianes';if(last.source)try{evaluate()}catch{}};$('calcToAnswer').onclick=()=>{try{const r=last.source?last:evaluate();const input=document.querySelector('#questionOptions input[type="number"]');if(input&&Number.isSafeInteger(r.decimal)){input.value=String(r.decimal);input.focus();$('calcStatus').textContent='Resultado entero copiado a la respuesta'}else $('calcStatus').textContent='La pregunta actual se responde mediante selección.'}catch{}};reset()}
window.ECOMATCalculator={init,open,close,evaluate,getLast:()=>({...last})};addEventListener('DOMContentLoaded',init);
})();
