/* Variantes adicionales: número entero, V/F y afirmaciones I–IV. */
(()=>{
  const L=s=>`\\(${s}\\)`, rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  function numeric(prompt,answer,hint,feedback,solution){return{type:'numeric',prompt,answer,hint,feedback,solution,options:[]}}
  function choice(prompt,options,answer,hint,feedback,solution,type='choice'){const correct=options[answer];let opts=options.slice();if(type==='statements'){for(const x of ['Solo II','Solo III','I y III'])if(opts.length<6&&!opts.includes(x))opts.push(x)}else if(type==='choice'){for(const x of ['No se puede determinar','Ninguna de las anteriores','Información insuficiente'])if(opts.length<6&&!opts.includes(x))opts.push(x)}if(type!=='truefalse')opts=opts.slice(0,6);const newAnswer=opts.indexOf(correct);return{type,prompt,options:opts,answer:newAnswer,hint,feedback,solution}}
  const extra={
    wronskiano2:{easy:[()=>choice(`Verdadero o falso: si ${L('W(y_1,y_2)(x_0)\\neq0')} en algún punto del intervalo, entonces las soluciones son linealmente independientes.`,['Verdadero','Falso'],0,'Usa el criterio del Wronskiano.','El Wronskiano no nulo garantiza independencia lineal.','El determinante fundamental es no nulo, por lo que ninguna solución es múltiplo de la otra.','truefalse')],hard:[()=>choice(`Considera: I. ${L('W=0')} puede indicar dependencia. II. Un conjunto fundamental de una EDO de orden dos contiene dos soluciones independientes. III. Abel usa el coeficiente de ${L("y'")}. ¿Cuáles son correctas?`,['Solo I','I y II','II y III','I, II y III'],3,'Revisa cada afirmación por separado.','Las tres afirmaciones son correctas en el contexto estándar.','I expresa el criterio usual; II usa la dimensión dos; III corresponde a la identidad de Abel.','statements')]},
    constantes2:{easy:[()=>{const a=rand(1,4),b=rand(a+1,7);return numeric(`La ecuación característica es ${L(`(r-${a})(r-${b})=0`)}. Escribe la raíz entera mayor.`,b,'Lee directamente los factores.','La raíz mayor es la asociada al factor con mayor constante.',`Las raíces son ${L(`r=${a}`)} y ${L(`r=${b}`)}; por tanto la mayor es ${b}.`)}],hard:[()=>choice(`Verdadero o falso: una raíz doble ${L('r=\\lambda')} produce ${L('y=(C_1+C_2x)e^{\\lambda x}')}.`,['Verdadero','Falso'],0,'Recuerda la segunda solución para multiplicidad dos.',`La segunda solución se multiplica por ${L('x')}.`,`La base fundamental es ${L('e^{\\lambda x}')} y ${L('xe^{\\lambda x}')}.`,'truefalse')]},
    cauchy2:{easy:[()=>{const m=rand(1,5);return numeric(`En una Cauchy–Euler la ecuación indicial es ${L(`(m-${m})(m+2)=0`)}. Escribe la raíz positiva.`,m,'Identifica la raíz del primer factor.','La raíz positiva es m.',`De ${L(`m-${m}=0`)} se obtiene ${L(`m=${m}`)}.`)}],hard:[()=>choice(`I. Se ensaya ${L('y=x^m')}. II. Una raíz repetida produce ${L('x^m\\ln x')}. III. Raíces complejas producen seno y coseno de ${L('\\ln x')}.`,['Solo I','I y II','II y III','I, II y III'],3,'Las tres describen casos estándar de Cauchy–Euler.','Todas son correctas.','Se aplican respectivamente al ensayo indicial, multiplicidad dos y raíces complejas.','statements')]},
    coef2:{easy:[()=>choice(`Verdadero o falso: para un forzamiento ${L('a\\cos(\\omega x)')} sin resonancia, el ensayo debe incluir seno y coseno.`,['Verdadero','Falso'],0,'Derivar coseno produce seno.','El conjunto de ensayo debe ser cerrado bajo derivación.',`Se usa ${L('A\\cos(\\omega x)+B\\sin(\\omega x)')}.`,'truefalse')],hard:[()=>{const k=rand(1,4);return numeric(`Si ${L(`y_p=Axe^{${k}x}`)} y el coeficiente hallado es ${L('A=3')}, escribe el coeficiente entero que multiplica a ${L(`xe^{${k}x}`)}.`,3,'El coeficiente ya aparece indicado.','El coeficiente solicitado es 3.',`La particular queda ${L('3xe^{kx}')}.`)} ]},
    reduccion2:{easy:[()=>choice(`Verdadero o falso: reducción de orden parte del ensayo ${L('y_2=v(x)y_1')}.`,['Verdadero','Falso'],0,'Se multiplica la solución conocida por una función desconocida.','Esa es la sustitución estándar.','Al sustituir se reduce el orden de la ecuación para v.','truefalse')],hard:[()=>choice(`I. Se requiere una solución no nula conocida. II. Aparece ${L('y_1^2')} en el denominador. III. La fórmula usa ${L('e^{-\\int P}')} en el numerador.`,['Solo I','I y II','II y III','I, II y III'],3,'Compara con la fórmula integral.','Las tres afirmaciones son correctas.','Todas aparecen en la fórmula de una segunda solución.','statements')]},
    parametros2:{easy:[()=>choice(`Verdadero o falso: en variación de parámetros ${L("u_1'=-y_2g/W")} lleva signo negativo.`,['Verdadero','Falso'],0,'Recuerda la regla de Cramer.','La fórmula estándar lleva signo negativo en u1\'.','Se obtiene al resolver el sistema auxiliar para u1\' y u2\'.','truefalse')],hard:[()=>{const w=rand(2,7);return numeric(`En un ejercicio se obtiene ${L(`W=${w}`)}. Escribe el valor entero del Wronskiano.`,w,'El valor está dado explícitamente.','El Wronskiano solicitado es el indicado.',`Por lectura directa, ${L(`W=${w}`)}.`)}]},
    masa2:{easy:[()=>{const m=rand(1,4),om=rand(2,5),k=m*om*om;return numeric(`Para ${L(`${m}x''+${k}x=0`)}, escribe la frecuencia natural entera ${L('\\omega_0=\\sqrt{k/m}')}.`,om,'Calcula la raíz cuadrada de k/m.',`La frecuencia natural es ${L('\\sqrt{k/m}')}.`,`${L(`\\omega_0=\\sqrt{${k}/${m}}=${om}`)}.`)}],hard:[()=>choice(`I. ${L('c^2-4mk<0')} implica subamortiguamiento. II. Igual a cero implica amortiguamiento crítico. III. Mayor que cero implica sobreamortiguamiento.`,['Solo I','I y II','II y III','I, II y III'],3,'Clasifica según el signo del discriminante.','Las tres clasificaciones son correctas.','El signo del discriminante físico determina el tipo de movimiento.','statements')]}
  };
  Object.entries(extra).forEach(([theme,levels])=>Object.entries(levels).forEach(([level,gens])=>{if(window.DIF_QUESTIONS?.[theme]?.[level])window.DIF_QUESTIONS[theme][level].push(...gens)}));
})();
